package com.assistmob.model.enums;

public enum AlertType {
    SOS_BUTTON,
    FALL_DETECTED,
    OBSTACLE_COLLISION,
    POTHOLE_HOLE_DETECTED,
    LOW_BATTERY,
    GEOFENCE_EXIT,
    DEVICE_OFFLINE,
    CHECKIN_SAFE,
    TREMOR_DETECTED,
    FATIGUE_WARNING,
    MEDICATION_REMINDER
}
